# What is the name of the project board you wish to use?

projectBoard: sis-tasks

# What are the labels and corresponding columns you wish to track?
# Format:
# labelName: columnName

labelsColumns: 
   'To do': To do
   'Current Sprint': Current Sprint
   'In Progress': In Progress
   'Review': Review
   'Reviewer approved': Reviewer approved
   'Done': Done



# What are the default labels you wish to add to a new issue?

defaultLabels:
   - To do

# Where do you want the card to move to in the new column?
# Can be one of top, bottom, or after:<card_id>, 
# where <card_id> is the id value of a card in the same column
# Allowed values: top, bottom, after:

defaultColumnPosition: top

on: push
