version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/assets
    env_file:
      - .env
    ports:
      - "8000:8000"
  nginx:
    build: ./production/nginx
    volumes:
      - static:/static
    ports:
      - "81:81"
    depends_on:
      - django_gunicorn

volumes:
  static:
