version: '3.7'

services:
  django_gunicorn:
    volumes:
      - assets:/assets
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - assets:/assets
    ports:
      - "81:81"
    depends_on:
      - django_gunicorn

volumes:
  assets:
