# Generated by Django 3.1.7 on 2021-03-10 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import sis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogNumber', models.CharField(max_length=20, verbose_name='Number')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('credits_earned', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Credits')),
                ('grading_type', models.CharField(choices=[('GR', 'Graded'), ('CR', 'Credit/No Credit')], default='GR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('abbreviation', sis.models.UpperField(max_length=6, primary_key=True, serialize=False, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('administrators', models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('professors', models.ManyToManyField(blank=True, related_name='prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xxx', max_length=20, verbose_name='Name')),
                ('date_registration_opens', models.DateField(verbose_name='Registration Opens')),
                ('date_started', models.DateField(verbose_name='Classes Start')),
                ('date_last_drop', models.DateField(verbose_name='Last Drop')),
                ('date_ended', models.DateField(verbose_name='Classes End')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Section Number')),
                ('textbooks', models.CharField(blank=True, max_length=256, verbose_name='Textbooks')),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
                ('waitlist_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waitlist Capacity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Your Mailing Address', max_length=256, verbose_name='Address')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Your Primary Contact Phone', max_length=31)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.major'),
        ),
    ]
