# Generated by Django 3.1.7 on 2021-03-13 08:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogNumber', models.CharField(max_length=20, verbose_name='Number')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('credits_earned', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Credits')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('abbreviation', sis.models.UpperField(max_length=6, primary_key=True, serialize=False, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('courses_required', models.ManyToManyField(blank=True, related_name='required_by', to='sis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Section Number')),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.course')),
            ],
        ),
        migrations.CreateModel(
            name='SectionStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(blank=True, choices=[(4, 'A'), (3, 'B'), (2, 'C'), (1, 'D'), (0, 'F')], default=0, null=True)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Done', 'Awaiting Grade'), ('Graded', 'Graded'), ('DropReq', 'Drop Requested'), ('Dropped', 'Dropped')], default='Registered', max_length=20, verbose_name='Course Status')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.section')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('date_registration_opens', models.DateField(verbose_name='Registration Opens')),
                ('date_started', models.DateField(verbose_name='Classes Start')),
                ('date_last_drop', models.DateField(verbose_name='Last Drop')),
                ('date_ended', models.DateField(verbose_name='Classes End')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis.major')),
                ('sections', models.ManyToManyField(related_name='students', through='sis.SectionStudent', to='sis.Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(verbose_name='Date Requested')),
                ('date_fulfilled', models.DateField(blank=True, null=True, verbose_name='Date Fulfilled')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.student')),
            ],
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.student'),
        ),
        migrations.AddField(
            model_name='section',
            name='enrolled',
            field=models.ManyToManyField(related_name='enrolled', through='sis.SectionStudent', to='sis.Student'),
        ),
        migrations.AddField(
            model_name='section',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.professor'),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.semester'),
        ),
        migrations.AddField(
            model_name='major',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='prof', to='sis.Professor'),
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_course', to='sis.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_prerequisite', to='sis.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.major'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(related_name='_course_prereqs_+', through='sis.CoursePrerequisite', to='sis.Course'),
        ),
    ]
