# Generated by Django 3.1.7 on 2021-03-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(default='xxx', max_length=10, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(help_text='Your Mailing Address', max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Your Full Name', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='capability',
            field=models.CharField(choices=[('ADMIN', 'full admin'), ('LOGIN', 'can log in'), ('CLASS_EDIT', 'can create and edit classes and sections'), ('SEM_EDIT', 'can create and edit semesters'), ('SEC_EDIT', 'can edit section values'), ('GRADE_EDIT', 'can enter and edit grades')], default='LOGIN', max_length=16, verbose_name='Capability'),
        ),
    ]
