# Generated by Django 3.1.7 on 2021-03-09 08:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sis.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogNumber', models.CharField(max_length=20, verbose_name='Number')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('creditsEarned', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Credits')),
                ('gradingType', models.CharField(choices=[('GR', 'Graded'), ('CR', 'Credit/No Credit')], default='GR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('abbreviation', sis.models.UpperField(max_length=6, primary_key=True, serialize=False, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('professors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Section Number')),
                ('textbooks', models.CharField(blank=True, max_length=256, verbose_name='Textbooks')),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
                ('waitlist_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sis.person')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('abbreviation', sis.models.UpperField(max_length=6, primary_key=True, serialize=False, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='majors',
            field=models.ManyToManyField(to='sis.Major'),
        ),
    ]
