# Generated by Django 3.1.7 on 2021-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionstudent',
            name='grade',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'A'), (3, 'B'), (2, 'C'), (1, 'D'), (0, 'F')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Done', 'Done'), ('Graded', 'Graded'), ('Drop Requested', 'Drop Requested'), ('Dropped', 'Dropped'), ('Waitlisted', 'Waitlisted')], default='Registered', max_length=20, verbose_name='Student Status'),
        ),
    ]
