# Generated by Django 3.1.7 on 2021-04-15 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Interval Amount')),
                ('interval_type', models.CharField(choices=[('minutes', 'minutes'), ('weeks', 'weeks'), ('seconds', 'seconds'), ('months', 'months'), ('hours', 'hours'), ('days', 'days')], max_length=7, verbose_name='Interval Type')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProbationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, verbose_name='Date')),
                ('frequency_type', models.CharField(choices=[('interval', 'interval'), (None, 'immediate'), ('date', 'date')], max_length=8, verbose_name='Frequency Type')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('interval', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sis.interval')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
