# Generated by Django 3.1.7 on 2021-04-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_academicprobationtask_interval_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='academicprobationtask',
            name='interval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.interval'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('minutes', 'minutes'), ('months', 'months'), ('seconds', 'seconds'), ('days', 'days'), ('weeks', 'weeks'), ('hours', 'hours')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
