# Generated by Django 3.1.7 on 2021-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_auto_20210308_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(default='xxx', max_length=20, verbose_name='name'),
        ),
    ]
