# Generated by Django 3.1.7 on 2021-03-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_remove_section_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='hours',
            field=models.CharField(default='MWF 0900-1000', max_length=256, verbose_name='Hours'),
            preserve_default=False,
        ),
    ]
