# Generated by Django 3.1.7 on 2021-03-09 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sis', '0002_auto_20210309_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='majors',
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sis.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='professors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
