# Generated by Django 3.1.7 on 2021-03-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_auto_20210309_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creditsEarned',
            new_name='credits_earned',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='gradingType',
            new_name='grading_type',
        ),
    ]
