# Generated by Django 3.1.7 on 2021-03-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_auto_20210326_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sections',
        ),
    ]
