# Generated by Django 3.1.7 on 2021-03-09 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0004_auto_20210309_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='waitlist_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waitlist Capacity'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(default='xxx', max_length=20, verbose_name='Name'),
        ),
    ]
