# Generated by Django 3.1.7 on 2021-03-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0004_auto_20210308_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='account_active',
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_class_admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_grade_editor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_semester_admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
