# Generated by Django 3.1.7 on 2021-03-10 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sis', '0005_auto_20210309_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='major',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(default='ARCH', on_delete=django.db.models.deletion.CASCADE, to='sis.major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='major',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='major',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='prof', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='major',
            field=models.ForeignKey(default='ARCH', on_delete=django.db.models.deletion.DO_NOTHING, to='sis.major'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
