# Generated by Django 3.1.7 on 2021-04-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20210415_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('weeks', 'weeks'), ('minutes', 'minutes'), ('hours', 'hours'), ('months', 'months'), ('seconds', 'seconds'), ('days', 'days')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
