# Generated by Django 3.1.7 on 2021-03-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20210317_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer')], default='FA', max_length=6, verbose_name='semester'),
        ),
    ]
