# Generated by Django 3.1.7 on 2021-03-08 07:22

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20210308_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, help_text='Your Mailing Address', max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='Your Primary Email Address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Your Primary Contact Phone', max_length=31),
        ),
    ]
