# Generated by Django 3.1.7 on 2021-04-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0006_auto_20210415_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[(None, 'immediate'), ('interval', 'interval'), ('date', 'date')], max_length=8, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days'), ('weeks', 'weeks'), ('seconds', 'seconds'), ('months', 'months')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
