# Generated by Django 3.1.7 on 2021-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_auto_20210415_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[('date', 'date'), (None, 'immediate'), ('interval', 'interval')], max_length=8, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('weeks', 'weeks'), ('seconds', 'seconds'), ('minutes', 'minutes'), ('days', 'days'), ('hours', 'hours'), ('months', 'months')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
