# Generated by Django 3.1.7 on 2021-04-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0008_auto_20210415_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[('interval', 'interval'), (None, 'immediate'), ('date', 'date')], max_length=8, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('days', 'days'), ('months', 'months'), ('seconds', 'seconds'), ('weeks', 'weeks'), ('minutes', 'minutes'), ('hours', 'hours')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
