# Generated by Django 3.1.7 on 2021-04-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0009_auto_20210415_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('hours', 'hours'), ('months', 'months'), ('seconds', 'seconds'), ('minutes', 'minutes')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
