# Generated by Django 3.1.7 on 2021-04-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0011_auto_20210415_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[('date', 'date'), ('interval', 'interval'), (None, 'immediate')], max_length=8, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('hours', 'hours'), ('months', 'months'), ('minutes', 'minutes'), ('days', 'days'), ('seconds', 'seconds'), ('weeks', 'weeks')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
