# Generated by Django 3.1.7 on 2021-04-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0015_auto_20210415_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('weeks', 'weeks'), ('hours', 'hours'), ('days', 'days'), ('months', 'months'), ('seconds', 'seconds'), ('minutes', 'minutes')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
