# Generated by Django 3.1.7 on 2021-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0017_auto_20210416_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[('interval', 'interval'), ('date', 'date'), ('immediate', 'immediate')], max_length=9, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('minutes', 'minutes'), ('days', 'days'), ('months', 'months'), ('seconds', 'seconds'), ('weeks', 'weeks'), ('hours', 'hours')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
