# Generated by Django 3.1.7 on 2021-04-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0018_auto_20210417_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[('immediate', 'immediate'), ('interval', 'interval'), ('date', 'date')], max_length=9, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('weeks', 'weeks'), ('seconds', 'seconds'), ('days', 'days'), ('hours', 'hours'), ('minutes', 'minutes'), ('months', 'months')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
