# Generated by Django 3.1.7 on 2021-04-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0021_auto_20210418_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[('immediate', 'immediate'), ('date', 'date'), ('interval', 'interval')], max_length=9, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('seconds', 'seconds'), ('hours', 'hours'), ('weeks', 'weeks'), ('minutes', 'minutes'), ('months', 'months'), ('days', 'days')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
