# Generated by Django 3.1.7 on 2021-04-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0022_auto_20210418_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprobationtask',
            name='frequency_type',
            field=models.CharField(choices=[('interval', 'interval'), ('date', 'date'), ('immediate', 'immediate')], max_length=9, verbose_name='Frequency Type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_type',
            field=models.CharField(choices=[('hours', 'hours'), ('weeks', 'weeks'), ('days', 'days'), ('minutes', 'minutes'), ('months', 'months'), ('seconds', 'seconds')], max_length=7, verbose_name='Interval Type'),
        ),
    ]
