name: Django Student Information System Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - name: Set up Python
    uses: actions/setup-python@v1
    with:
      python-version: 3.7
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install requirements.txt
  - name: Run migrations
    run: python manage.py migrate
  - name: Run tests
    run: python manage.py test
