name: Django Student Information System Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./production/requirements.txt
    - name: Run migrations
      run: |
        cd student-info-system
        python manage.py migrate
    - name: Run tests
      run: |
        cd student-info-system
        python manage.py test
